import test from 'node:test';
import assert from 'node:assert/strict';
import {
  approveJournal,
  postJournal,
  submitJournal,
  syncOperationalJournals
} from '../server/services/journals.js';
import {
  buildRelatedPartyCloseReconciliation,
  createHistoricalCleanupJournal,
  generateIntercompanyEliminationJournals
} from '../server/services/related-party-close.js';
import { makeDb } from './helpers/finance-fixture.js';

function makeAccounts() {
  return [
    { id: 'ACC-US', name: 'BoFA Operating', entity: 'US', currency: 'USD', accountRole: 'BANK', status: 'ACTIVE' },
    { id: 'ACC-UK', name: 'Wise USD', entity: 'UK', currency: 'USD', accountRole: 'BANK', status: 'ACTIVE' }
  ];
}

test('elimination journals are generated explicitly and duplicate generation reuses the active journal', () => {
  const db = makeDb({
    accounts: makeAccounts(),
    intercompanyEntries: [
      {
        id: 'IC-1',
        date: '2026-03-01',
        fromEntity: 'US',
        toEntity: 'UK',
        amount: 200,
        currency: 'USD',
        status: 'OPEN',
        sourceAccountId: 'ACC-US',
        receivingSourceAccountId: 'ACC-UK',
        reference: 'IC-REF-1',
        repaymentEvents: []
      }
    ]
  });

  syncOperationalJournals(db, 'USR-1');

  const first = generateIntercompanyEliminationJournals(db, {
    periodKey: '2026-03',
    actor: { id: 'USR-1', role: 'ADMIN' }
  });
  const second = generateIntercompanyEliminationJournals(db, {
    periodKey: '2026-03',
    actor: { id: 'USR-1', role: 'ADMIN' }
  });

  assert.equal(first.summary.created, 1);
  assert.equal(second.summary.created, 0);
  assert.equal(second.summary.reused, 1);
  const activeEliminations = db.journals.filter((row) => row.journalType === 'ELIMINATION' && !row.reversedByJournalId);
  assert.equal(activeEliminations.length, 1);
  assert.equal(activeEliminations[0].consolidationOnly, true);
  assert.equal(activeEliminations[0].periodKey, '2026-03');
  assert.equal(activeEliminations[0].eliminationKey, 'US->UK');
});

test('close reconciliation flags mismatched related-party balances as blockers', () => {
  const db = makeDb({
    intercompanyEntries: [
      {
        id: 'IC-2',
        date: '2026-03-05',
        fromEntity: 'US',
        toEntity: 'UK',
        amount: 125,
        currency: 'USD',
        status: 'OPEN',
        reference: 'IC-REF-2',
        repaymentEvents: []
      }
    ]
  });

  const reconciliation = buildRelatedPartyCloseReconciliation(db, { periodKey: '2026-03' });
  assert.equal(reconciliation.summary.mismatchPairCount, 1);
  assert.equal(reconciliation.summary.relatedPartyCloseReady, false);
  assert.equal(reconciliation.pairs[0].eliminationStatus, 'BLOCKED_MISMATCH');
});

test('historical related-party cleanup creates a controlled adjustment journal and prevents duplicates', () => {
  const db = makeDb({
    journals: [
      {
        id: 'JRN-LEGACY',
        journalNumber: 'JRN-LEGACY',
        journalType: 'MANUAL',
        sourceType: 'MANUAL',
        sourceId: 'LEGACY-1',
        entity: 'US',
        currency: 'USD',
        postingDate: '2026-03-10',
        memo: 'Legacy related-party posting',
        status: 'POSTED',
        createdByUserId: 'USR-2',
        approvedByUserId: 'USR-1',
        postedByUserId: 'USR-2',
        autoGenerated: false,
        createdAt: '2026-03-10T00:00:00Z',
        updatedAt: '2026-03-10T00:00:00Z',
        submittedAt: '2026-03-10T00:00:00Z',
        approvedAt: '2026-03-10T00:00:00Z',
        postedAt: '2026-03-10T00:00:00Z',
        lines: [
          {
            id: 'JRL-1',
            lineNumber: 1,
            globalAccountId: 'GLA-4',
            globalAccountCode: '1200',
            globalAccountName: 'Due from Related Parties',
            globalAccountType: 'ASSET',
            description: 'Legacy related-party asset',
            entity: 'US',
            currency: 'USD',
            debit: 150,
            credit: 0,
            reportingRate: 1,
            createdAt: '2026-03-10T00:00:00Z',
            updatedAt: '2026-03-10T00:00:00Z'
          },
          {
            id: 'JRL-2',
            lineNumber: 2,
            globalAccountId: 'GLA-1',
            globalAccountCode: '1000',
            globalAccountName: 'Cash and Cash Equivalents',
            globalAccountType: 'ASSET',
            description: 'Offset',
            entity: 'US',
            currency: 'USD',
            debit: 0,
            credit: 150,
            reportingRate: 1,
            createdAt: '2026-03-10T00:00:00Z',
            updatedAt: '2026-03-10T00:00:00Z'
          }
        ]
      }
    ]
  });

  const reconciliation = buildRelatedPartyCloseReconciliation(db, { periodKey: '2026-03' });
  assert.equal(reconciliation.cleanupExceptions.length, 1);

  const created = createHistoricalCleanupJournal(db, {
    periodKey: '2026-03',
    exceptionId: reconciliation.cleanupExceptions[0].id,
    offsetGlobalAccountCode: '3000',
    postingDate: '2026-03-31',
    memo: 'Cleanup legacy related-party balance',
    actorUserId: 'USR-2'
  });

  assert.equal(created.duplicate, false);
  assert.equal(created.journal.status, 'DRAFT');
  assert.equal(created.journal.sourceType, 'RELATED_PARTY_CLEANUP');
  assert.equal(created.journal.cleanupKey, reconciliation.cleanupExceptions[0].id);

  submitJournal(db, created.journal.id, 'USR-2');
  approveJournal(db, created.journal.id, { id: 'USR-1', role: 'ADMIN' });
  postJournal(db, created.journal.id, { id: 'USR-2', role: 'ACCOUNTANT' });

  const duplicate = createHistoricalCleanupJournal(db, {
    periodKey: '2026-03',
    exceptionId: reconciliation.cleanupExceptions[0].id,
    offsetGlobalAccountCode: '3000',
    postingDate: '2026-03-31',
    memo: 'Cleanup legacy related-party balance',
    actorUserId: 'USR-2'
  });

  assert.equal(duplicate.duplicate, true);
  assert.equal(duplicate.journal.id, created.journal.id);
});
